-- Add reservation period columns to quotation table
-- Schema: BI_NEGT_KSAISUZU

ALTER TABLE "BI_NEGT_KSAISUZU"."DMS_QUOTATION"
ADD (
  "VEHICLE_RESERVATION_FROM_DATE" NVARCHAR(30) NULL,
  "VEHICLE_RESERVATION_TO_DATE" NVARCHAR(30) NULL
);
