-- SAP SO/SQ integration tracking table
-- Keeps staging/queue state outside DMS_QUOTATION and DMS_SALES_ORDER

CREATE COLUMN TABLE "BI_NEGT_KSAISUZU"."DMS_SO_SQ_INTEGRATION_LOG" (
  "SLNO" INTEGER NOT NULL,
  "SOURCE_TYPE" NVARCHAR(30) NOT NULL,
  "SOURCE_SLNO" INTEGER NOT NULL,
  "SOURCE_NUMBER" NVARCHAR(120),
  "ORDER_TYPE" NVARCHAR(10) NOT NULL,
  "STATUS" NVARCHAR(20) NOT NULL,
  "STAGING_SLNO" NVARCHAR(120),
  "STAGED_TYPE" NVARCHAR(20),
  "SAP_DOCENTRY" NVARCHAR(120),
  "REFERENCE_NUMBER" NVARCHAR(120),
  "REFERENCE_SOURCE" NVARCHAR(20),
  "REQUEST_PAYLOAD" NCLOB,
  "SUBMIT_RESPONSE" NCLOB,
  "QUEUE_RESPONSE" NCLOB,
  "ERROR_MESSAGE" NCLOB,
  "CREATED_BY" NVARCHAR(120) NOT NULL,
  "CREATED_DATE" NVARCHAR(30) NOT NULL,
  "UPDATED_BY" NVARCHAR(120),
  "UPDATED_DATE" NVARCHAR(30),
  "IS_DELETED" NVARCHAR(1) DEFAULT 'N' NOT NULL,
  PRIMARY KEY ("SLNO")
);

CREATE INDEX "IDX_SO_SQ_INTEGRATION_SOURCE"
  ON "BI_NEGT_KSAISUZU"."DMS_SO_SQ_INTEGRATION_LOG" ("SOURCE_TYPE", "SOURCE_SLNO");

