-- DMS EORDER staging objects for queue-based SAP reflection
-- Schema: BI_NEGT_KSAISUZU
--
-- Flow:
-- 1. Insert header into ECOMSOHD
-- 2. Insert lines into ECOMSOCH
-- 3. Use returned SLNO as WebSoNo for the queue worker

-- DROP TABLE "BI_NEGT_KSAISUZU"."ECOMSOCH";
-- DROP TABLE "BI_NEGT_KSAISUZU"."ECOMSOHD";

CREATE COLUMN TABLE "BI_NEGT_KSAISUZU"."ECOMSOHD" (
  "SLNO" INTEGER CS_INT NOT NULL,
  "ORDER_TYPE" NVARCHAR(2) NOT NULL,
  "SOURCE_TYPE" NVARCHAR(20) NOT NULL,
  "SOURCE_SLNO" INTEGER NOT NULL,
  "SOURCE_NUMBER" NVARCHAR(50),
  "CARDCODE" NVARCHAR(100),
  "CARDNAME" NVARCHAR(200),
  "ECOMDOCDATE" NVARCHAR(30),
  "ECOMDOCDUEDATE" NVARCHAR(30),
  "ECOMADDRESS" NVARCHAR(500),
  "DISCPRCNT" NVARCHAR(30),
  "INVOICETYPE" NVARCHAR(10),
  "DISCSUM" NVARCHAR(50),
  "DOCCUR" NVARCHAR(10),
  "DOCRATE" DECIMAL(19, 6),
  "DOCTOTAL" NVARCHAR(50),
  "COMMENTS" NCLOB,
  "DOCBRANCH" NVARCHAR(100),
  "U_AUTORELEASE" NVARCHAR(1),
  "U_SOSHIPMTYPE" INTEGER,
  "LOGUSERID" NVARCHAR(100),
  "USERLOG" NVARCHAR(100),
  "PICKRMRK" NVARCHAR(200),
  "NUMATCARD" NVARCHAR(255),
  "EXP_DELIVERY" NVARCHAR(1),
  "SLPCODE" NVARCHAR(50),
  "COMPANYBI" NVARCHAR(50),
  "QUEUE_COMPANY" NVARCHAR(50),
  "QUEUE_USER_ID" NVARCHAR(100),
  "QUEUE_ORDER_SRC" NVARCHAR(50),
  "QUEUE_STATUS" NVARCHAR(20),
  "QUEUE_MESSAGE" NVARCHAR(1000),
  "CREATED_BY" NVARCHAR(100),
  "CREATED_DATE" TIMESTAMP,
  "UPDATED_BY" NVARCHAR(100),
  "UPDATED_DATE" TIMESTAMP,
  "IS_DELETED" NVARCHAR(1) DEFAULT 'N' NOT NULL,
  PRIMARY KEY ("SLNO")
);

CREATE COLUMN TABLE "BI_NEGT_KSAISUZU"."ECOMSOCH" (
  "SLNO" INTEGER CS_INT NOT NULL,
  "WEBSONO" INTEGER NOT NULL,
  "LINE_BUCKET" NVARCHAR(20) NOT NULL,
  "LINENUM" INTEGER NOT NULL,
  "LOGUSERID" NVARCHAR(100),
  "USERLOG" NVARCHAR(100),
  "WHSCODE" NVARCHAR(50),
  "QUANTITY" INTEGER,
  "DISCPRCNT" NVARCHAR(30),
  "LINETOTAL" DECIMAL(19, 6),
  "VENDORNUM" NVARCHAR(100),
  "PRICEBEFDI" DECIMAL(19, 6),
  "VATPRCNT" DECIMAL(19, 6),
  "ECOMREFNUM" NVARCHAR(100),
  "TAXCODE" NVARCHAR(50),
  "ITEMCODE" NVARCHAR(100),
  "ITEMNAME" NVARCHAR(500),
  "UOM" NVARCHAR(50),
  "PRICE" DECIMAL(19, 6),
  "CURRENCY" NVARCHAR(10),
  "RATE" DECIMAL(19, 6),
  "U_ASTKNE31" DECIMAL(19, 6),
  "REQUESTEDPRICE" DECIMAL(19, 6),
  "DESCRIPTION" NCLOB,
  "CREATED_BY" NVARCHAR(100),
  "CREATED_DATE" TIMESTAMP,
  "IS_DELETED" NVARCHAR(1) DEFAULT 'N' NOT NULL,
  PRIMARY KEY ("SLNO")
);

-- DROP PROCEDURE "BI_NEGT_KSAISUZU"."ECOM_INSERT_ECOMSOHD";
CREATE PROCEDURE "BI_NEGT_KSAISUZU"."ECOM_INSERT_ECOMSOHD" (
  IN I_SLNO INTEGER,
  IN I_ORDER_TYPE NVARCHAR(2),
  IN I_SOURCE_TYPE NVARCHAR(20),
  IN I_SOURCE_SLNO INTEGER,
  IN I_SOURCE_NUMBER NVARCHAR(50),
  IN I_CARDCODE NVARCHAR(100),
  IN I_CARDNAME NVARCHAR(200),
  IN I_ECOMDOCDATE NVARCHAR(30),
  IN I_ECOMDOCDUEDATE NVARCHAR(30),
  IN I_ECOMADDRESS NVARCHAR(500),
  IN I_DISCPRCNT NVARCHAR(30),
  IN I_INVOICETYPE NVARCHAR(10),
  IN I_DISCSUM NVARCHAR(50),
  IN I_DOCCUR NVARCHAR(10),
  IN I_DOCRATE DECIMAL(19, 6),
  IN I_DOCTOTAL NVARCHAR(50),
  IN I_COMMENTS NCLOB,
  IN I_DOCBRANCH NVARCHAR(100),
  IN I_U_AUTORELEASE NVARCHAR(1),
  IN I_U_SOSHIPMTYPE INTEGER,
  IN I_LOGUSERID NVARCHAR(100),
  IN I_USERLOG NVARCHAR(100),
  IN I_PICKRMRK NVARCHAR(200),
  IN I_NUMATCARD NVARCHAR(255),
  IN I_EXP_DELIVERY NVARCHAR(1),
  IN I_SLPCODE NVARCHAR(50),
  IN I_COMPANYBI NVARCHAR(50),
  IN I_QUEUE_COMPANY NVARCHAR(50),
  IN I_QUEUE_USER_ID NVARCHAR(100),
  IN I_QUEUE_ORDER_SRC NVARCHAR(50),
  IN I_CREATED_BY NVARCHAR(100),
  IN I_CREATED_DATE NVARCHAR(19)
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
AS
BEGIN
  INSERT INTO "BI_NEGT_KSAISUZU"."ECOMSOHD" (
    "SLNO", "ORDER_TYPE", "SOURCE_TYPE", "SOURCE_SLNO", "SOURCE_NUMBER",
    "CARDCODE", "CARDNAME", "ECOMDOCDATE", "ECOMDOCDUEDATE", "ECOMADDRESS",
    "DISCPRCNT", "INVOICETYPE", "DISCSUM", "DOCCUR", "DOCRATE", "DOCTOTAL",
    "COMMENTS", "DOCBRANCH", "U_AUTORELEASE", "U_SOSHIPMTYPE",
    "LOGUSERID", "USERLOG", "PICKRMRK", "NUMATCARD", "EXP_DELIVERY",
    "SLPCODE", "COMPANYBI", "QUEUE_COMPANY", "QUEUE_USER_ID", "QUEUE_ORDER_SRC",
    "QUEUE_STATUS", "CREATED_BY", "CREATED_DATE", "IS_DELETED"
  ) VALUES (
    :I_SLNO, :I_ORDER_TYPE, :I_SOURCE_TYPE, :I_SOURCE_SLNO, :I_SOURCE_NUMBER,
    :I_CARDCODE, :I_CARDNAME, :I_ECOMDOCDATE, :I_ECOMDOCDUEDATE, :I_ECOMADDRESS,
    :I_DISCPRCNT, :I_INVOICETYPE, :I_DISCSUM, :I_DOCCUR, :I_DOCRATE, :I_DOCTOTAL,
    :I_COMMENTS, :I_DOCBRANCH, :I_U_AUTORELEASE, :I_U_SOSHIPMTYPE,
    :I_LOGUSERID, :I_USERLOG, :I_PICKRMRK, :I_NUMATCARD, :I_EXP_DELIVERY,
    :I_SLPCODE, :I_COMPANYBI, :I_QUEUE_COMPANY, :I_QUEUE_USER_ID, :I_QUEUE_ORDER_SRC,
    'Pending', :I_CREATED_BY, TO_TIMESTAMP(:I_CREATED_DATE, 'YYYY-MM-DD HH24:MI:SS'), 'N'
  );
END;

-- DROP PROCEDURE "BI_NEGT_KSAISUZU"."ECOM_INSERT_ECOMSOCH";
CREATE PROCEDURE "BI_NEGT_KSAISUZU"."ECOM_INSERT_ECOMSOCH" (
  IN I_SLNO INTEGER,
  IN I_WEBSONO INTEGER,
  IN I_LINE_BUCKET NVARCHAR(20),
  IN I_LINENUM INTEGER,
  IN I_LOGUSERID NVARCHAR(100),
  IN I_USERLOG NVARCHAR(100),
  IN I_WHSCODE NVARCHAR(50),
  IN I_QUANTITY INTEGER,
  IN I_DISCPRCNT NVARCHAR(30),
  IN I_LINETOTAL DECIMAL(19, 6),
  IN I_VENDORNUM NVARCHAR(100),
  IN I_PRICEBEFDI DECIMAL(19, 6),
  IN I_VATPRCNT DECIMAL(19, 6),
  IN I_ECOMREFNUM NVARCHAR(100),
  IN I_TAXCODE NVARCHAR(50),
  IN I_ITEMCODE NVARCHAR(100),
  IN I_ITEMNAME NVARCHAR(500),
  IN I_UOM NVARCHAR(50),
  IN I_PRICE DECIMAL(19, 6),
  IN I_CURRENCY NVARCHAR(10),
  IN I_RATE DECIMAL(19, 6),
  IN I_U_ASTKNE31 DECIMAL(19, 6),
  IN I_REQUESTEDPRICE DECIMAL(19, 6),
  IN I_DESCRIPTION NCLOB,
  IN I_CREATED_BY NVARCHAR(100),
  IN I_CREATED_DATE NVARCHAR(19)
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
AS
BEGIN
  INSERT INTO "BI_NEGT_KSAISUZU"."ECOMSOCH" (
    "SLNO", "WEBSONO", "LINE_BUCKET", "LINENUM",
    "LOGUSERID", "USERLOG", "WHSCODE", "QUANTITY", "DISCPRCNT",
    "LINETOTAL", "VENDORNUM", "PRICEBEFDI", "VATPRCNT", "ECOMREFNUM",
    "TAXCODE", "ITEMCODE", "ITEMNAME", "UOM", "PRICE", "CURRENCY",
    "RATE", "U_ASTKNE31", "REQUESTEDPRICE", "DESCRIPTION",
    "CREATED_BY", "CREATED_DATE", "IS_DELETED"
  ) VALUES (
    :I_SLNO, :I_WEBSONO, :I_LINE_BUCKET, :I_LINENUM,
    :I_LOGUSERID, :I_USERLOG, :I_WHSCODE, :I_QUANTITY, :I_DISCPRCNT,
    :I_LINETOTAL, :I_VENDORNUM, :I_PRICEBEFDI, :I_VATPRCNT, :I_ECOMREFNUM,
    :I_TAXCODE, :I_ITEMCODE, :I_ITEMNAME, :I_UOM, :I_PRICE, :I_CURRENCY,
    :I_RATE, :I_U_ASTKNE31, :I_REQUESTEDPRICE, :I_DESCRIPTION,
    :I_CREATED_BY, TO_TIMESTAMP(:I_CREATED_DATE, 'YYYY-MM-DD HH24:MI:SS'), 'N'
  );
END;

-- Optional grants
-- GRANT EXECUTE ON PROCEDURE "BI_NEGT_KSAISUZU"."ECOM_INSERT_ECOMSOHD" TO "NETUSR";
-- GRANT EXECUTE ON PROCEDURE "BI_NEGT_KSAISUZU"."ECOM_INSERT_ECOMSOCH" TO "NETUSR";
