-- Add charge columns to sales enquiry table (run once)
-- Schema: BI_NEGT_KSAISUZU

ALTER TABLE "BI_NEGT_KSAISUZU"."DMS_SALESENQUIRY"
ADD ("CHARGECODE" NVARCHAR(100));

ALTER TABLE "BI_NEGT_KSAISUZU"."DMS_SALESENQUIRY"
ADD ("CHARGENAME" NVARCHAR(255));

ALTER TABLE "BI_NEGT_KSAISUZU"."DMS_SALESENQUIRY"
ADD ("CHARGEPRICE" NVARCHAR(100));

ALTER TABLE "BI_NEGT_KSAISUZU"."DMS_SALESENQUIRY"
ADD ("CHARGE" NCLOB);
