-- Bank Funding / Financing Schemes SPs
-- Procedure schema: BI_NEGT_KSAISUZU
-- Table schema: BI_NEGT_KSAISUZU

-- 100031: Get financing schemes by enquiry
-- DROP PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100031_EORDER";
CREATE PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100031_EORDER" (
  IN I_ENQUIRY_SLNO INTEGER
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
AS
BEGIN
  SELECT *
  FROM "BI_NEGT_KSAISUZU"."DMS_ENQUIRY_FINANCING"
  WHERE "ENQUIRY_SLNO" = :I_ENQUIRY_SLNO
    AND "IS_DELETED" = 'N'
  ORDER BY "CREATED_DATE" DESC;
END;

-- 100032: Get financing scheme by ID
-- DROP PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100032_EORDER";
CREATE PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100032_EORDER" (
  IN I_SLNO INTEGER
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
AS
BEGIN
  SELECT *
  FROM "BI_NEGT_KSAISUZU"."DMS_ENQUIRY_FINANCING"
  WHERE "SLNO" = :I_SLNO
    AND "IS_DELETED" = 'N';
END;


-- 100033: Create financing scheme
-- DROP PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100033_EORDER";
CREATE PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100033_EORDER" (
  IN I_ENQUIRY_SLNO INTEGER,
  IN I_LENDER_CODE NVARCHAR(100),
  IN I_LENDER_NAME NVARCHAR(200),
  IN I_SCHEME_NAME NVARCHAR(200),
  IN I_CURRENCY NVARCHAR(10),
  IN I_VEHICLE_PRICE DECIMAL(19, 6),
  IN I_DOWNPAYMENT DECIMAL(19, 6),
  IN I_DOWNPAYMENT_PERCENT DECIMAL(9, 4),
  IN I_TRADE_IN_VALUE DECIMAL(19, 6),
  IN I_FINANCE_AMOUNT DECIMAL(19, 6),
  IN I_TERM_MONTHS INTEGER,
  IN I_INTEREST_RATE DECIMAL(9, 4),
  IN I_MONTHLY_PAYMENT DECIMAL(19, 6),
  IN I_TOTAL_INTEREST DECIMAL(19, 6),
  IN I_FDA DECIMAL(19, 6),
  IN I_GPV_BALLOON DECIMAL(19, 6),
  IN I_SALE_CODE NVARCHAR(100),
  IN I_STATUS NVARCHAR(20),
  IN I_IS_SELECTED NVARCHAR(1),
  IN I_CREATED_BY NVARCHAR(100),
  IN I_CREATED_DATE NVARCHAR(19)
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
AS
BEGIN
  DECLARE V_NEXT_SLNO INTEGER;

  SELECT COALESCE(MAX("SLNO"), 0) + 1
    INTO V_NEXT_SLNO
  FROM "BI_NEGT_KSAISUZU"."DMS_ENQUIRY_FINANCING";

  INSERT INTO "BI_NEGT_KSAISUZU"."DMS_ENQUIRY_FINANCING" (
    "SLNO", "ENQUIRY_SLNO", "LENDER_CODE", "LENDER_NAME", "SCHEME_NAME", "CURRENCY",
    "VEHICLE_PRICE", "DOWNPAYMENT", "DOWNPAYMENT_PERCENT", "TRADE_IN_VALUE",
    "FINANCE_AMOUNT", "TERM_MONTHS", "INTEREST_RATE", "MONTHLY_PAYMENT",
    "TOTAL_INTEREST", "FDA", "GPV_BALLOON", "SALE_CODE",
    "STATUS", "IS_SELECTED",
    "CREATED_BY", "CREATED_DATE", "IS_DELETED"
  ) VALUES (
    :V_NEXT_SLNO, :I_ENQUIRY_SLNO, :I_LENDER_CODE, :I_LENDER_NAME, :I_SCHEME_NAME, :I_CURRENCY,
    :I_VEHICLE_PRICE, :I_DOWNPAYMENT, :I_DOWNPAYMENT_PERCENT, :I_TRADE_IN_VALUE,
    :I_FINANCE_AMOUNT, :I_TERM_MONTHS, :I_INTEREST_RATE, :I_MONTHLY_PAYMENT,
    :I_TOTAL_INTEREST, :I_FDA, :I_GPV_BALLOON, :I_SALE_CODE,
    :I_STATUS, :I_IS_SELECTED,
    :I_CREATED_BY, TO_TIMESTAMP(:I_CREATED_DATE, 'YYYY-MM-DD HH24:MI:SS'), 'N'
  );
END;

-- 100034: Update financing scheme
-- DROP PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100034_EORDER";
CREATE PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100034_EORDER" (
  IN I_SLNO INTEGER,
  IN I_LENDER_CODE NVARCHAR(100),
  IN I_LENDER_NAME NVARCHAR(200),
  IN I_SCHEME_NAME NVARCHAR(200),
  IN I_CURRENCY NVARCHAR(10),
  IN I_VEHICLE_PRICE DECIMAL(19, 6),
  IN I_DOWNPAYMENT DECIMAL(19, 6),
  IN I_DOWNPAYMENT_PERCENT DECIMAL(9, 4),
  IN I_TRADE_IN_VALUE DECIMAL(19, 6),
  IN I_FINANCE_AMOUNT DECIMAL(19, 6),
  IN I_TERM_MONTHS INTEGER,
  IN I_INTEREST_RATE DECIMAL(9, 4),
  IN I_MONTHLY_PAYMENT DECIMAL(19, 6),
  IN I_TOTAL_INTEREST DECIMAL(19, 6),
  IN I_FDA DECIMAL(19, 6),
  IN I_GPV_BALLOON DECIMAL(19, 6),
  IN I_SALE_CODE NVARCHAR(100),
  IN I_STATUS NVARCHAR(20),
  IN I_IS_SELECTED NVARCHAR(1),
  IN I_UPDATED_BY NVARCHAR(100),
  IN I_UPDATED_DATE NVARCHAR(19)
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
AS
BEGIN
  UPDATE "BI_NEGT_KSAISUZU"."DMS_ENQUIRY_FINANCING"
  SET "LENDER_CODE" = :I_LENDER_CODE,
      "LENDER_NAME" = :I_LENDER_NAME,
      "SCHEME_NAME" = :I_SCHEME_NAME,
      "CURRENCY" = :I_CURRENCY,
      "VEHICLE_PRICE" = :I_VEHICLE_PRICE,
      "DOWNPAYMENT" = :I_DOWNPAYMENT,
      "DOWNPAYMENT_PERCENT" = :I_DOWNPAYMENT_PERCENT,
      "TRADE_IN_VALUE" = :I_TRADE_IN_VALUE,
      "FINANCE_AMOUNT" = :I_FINANCE_AMOUNT,
      "TERM_MONTHS" = :I_TERM_MONTHS,
      "INTEREST_RATE" = :I_INTEREST_RATE,
      "MONTHLY_PAYMENT" = :I_MONTHLY_PAYMENT,
      "TOTAL_INTEREST" = :I_TOTAL_INTEREST,
      "FDA" = :I_FDA,
      "GPV_BALLOON" = :I_GPV_BALLOON,
      "SALE_CODE" = :I_SALE_CODE,
      "STATUS" = :I_STATUS,
      "IS_SELECTED" = :I_IS_SELECTED,
      "UPDATED_BY" = :I_UPDATED_BY,
      "UPDATED_DATE" = TO_TIMESTAMP(:I_UPDATED_DATE, 'YYYY-MM-DD HH24:MI:SS')
  WHERE "SLNO" = :I_SLNO
    AND "IS_DELETED" = 'N';
END;

-- 100035: Soft delete financing scheme
-- DROP PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100035_EORDER";
CREATE PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100035_EORDER" (
  IN I_SLNO INTEGER,
  IN I_UPDATED_BY NVARCHAR(100),
  IN I_UPDATED_DATE NVARCHAR(19)
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
AS
BEGIN
  UPDATE "BI_NEGT_KSAISUZU"."DMS_ENQUIRY_FINANCING"
  SET "IS_DELETED" = 'Y',
      "UPDATED_BY" = :I_UPDATED_BY,
      "UPDATED_DATE" = TO_TIMESTAMP(:I_UPDATED_DATE, 'YYYY-MM-DD HH24:MI:SS')
  WHERE "SLNO" = :I_SLNO;
END;

-- 100036: Get active lenders
-- DROP PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100036_EORDER";
CREATE PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100036_EORDER" ()
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
AS
BEGIN
  SELECT *
  FROM "BI_NEGT_KSAISUZU"."DMS_LENDERS"
  WHERE "IS_ACTIVE" = 'Y'
  ORDER BY "LENDER_NAME";
END;

-- 100037: Set preferred financing scheme
-- DROP PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100037_EORDER";
CREATE PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100037_EORDER" (
  IN I_SLNO INTEGER,
  IN I_ENQUIRY_SLNO INTEGER,
  IN I_UPDATED_BY NVARCHAR(100),
  IN I_UPDATED_DATE NVARCHAR(19)
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
AS
BEGIN
  UPDATE "BI_NEGT_KSAISUZU"."DMS_ENQUIRY_FINANCING"
  SET "IS_SELECTED" = 'N',
      "UPDATED_BY" = :I_UPDATED_BY,
      "UPDATED_DATE" = TO_TIMESTAMP(:I_UPDATED_DATE, 'YYYY-MM-DD HH24:MI:SS')
  WHERE "ENQUIRY_SLNO" = :I_ENQUIRY_SLNO
    AND "IS_DELETED" = 'N';

  UPDATE "BI_NEGT_KSAISUZU"."DMS_ENQUIRY_FINANCING"
  SET "IS_SELECTED" = 'Y',
      "UPDATED_BY" = :I_UPDATED_BY,
      "UPDATED_DATE" = TO_TIMESTAMP(:I_UPDATED_DATE, 'YYYY-MM-DD HH24:MI:SS')
  WHERE "SLNO" = :I_SLNO
    AND "IS_DELETED" = 'N';
END;

-- Optional grants:
-- GRANT EXECUTE ON "BI_NEGT_KSAISUZU"."DMS_KSA_100031_EORDER" TO "NETUSR";
-- GRANT EXECUTE ON "BI_NEGT_KSAISUZU"."DMS_KSA_100032_EORDER" TO "NETUSR";
-- GRANT EXECUTE ON "BI_NEGT_KSAISUZU"."DMS_KSA_100033_EORDER" TO "NETUSR";
-- GRANT EXECUTE ON "BI_NEGT_KSAISUZU"."DMS_KSA_100034_EORDER" TO "NETUSR";
-- GRANT EXECUTE ON "BI_NEGT_KSAISUZU"."DMS_KSA_100035_EORDER" TO "NETUSR";
-- GRANT EXECUTE ON "BI_NEGT_KSAISUZU"."DMS_KSA_100036_EORDER" TO "NETUSR";
-- GRANT EXECUTE ON "BI_NEGT_KSAISUZU"."DMS_KSA_100037_EORDER" TO "NETUSR";
