-- DMS_KSA_100006_EORDER: Create Sales Enquiry
-- Schema: BI_NEGT_KSAISUZU
-- Matches backend parameter order in enquiry.service.ts (44 IN params)

-- If procedure already exists, drop it first (run manually if needed):
-- DROP PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100006_EORDER";

CREATE PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100006_EORDER" (
  IN I_CUSTOMERID NVARCHAR(50),
  IN I_CUSTOMERNAME NVARCHAR(200),
  IN I_ADDRESS NVARCHAR(500),
  IN I_POSTCODE NVARCHAR(20),
  IN I_HOMEPHONE NVARCHAR(50),
  IN I_WORKPHONE NVARCHAR(50),
  IN I_MOBILE NVARCHAR(50),
  IN I_HOMEEMAIL NVARCHAR(200),
  IN I_MAKE NVARCHAR(100),
  IN I_MAKENAME NVARCHAR(200),
  IN I_MODEL NVARCHAR(100),
  IN I_MODELNAME NVARCHAR(200),
  IN I_VARIANT NVARCHAR(100),
  IN I_VARIANTNAME NVARCHAR(200),
  IN I_YEAR NVARCHAR(10),
  IN I_COLOR NVARCHAR(100),
  IN I_SUPPCATNUM NVARCHAR(100),
  IN I_MODELCODE NVARCHAR(100),
  IN I_QUANTITY INTEGER,
  IN I_VINNUMBER NVARCHAR(100),
  IN I_VINDETAILS NCLOB,
  IN I_BRANCH NVARCHAR(100),
  IN I_BRANCHNAME NVARCHAR(200),
  IN I_BUDGET NVARCHAR(100),
  IN I_FINANCING NVARCHAR(20),
  IN I_PREFERREDCONTACT NVARCHAR(50),
  IN I_PREFERREDTIME NVARCHAR(50),
  IN I_PREFERREDDELIVERY NVARCHAR(200),
  IN I_SOURCE NVARCHAR(100),
  IN I_SALESTYPE NVARCHAR(50),
  IN I_TRADEINMAKE NVARCHAR(100),
  IN I_TRADEINMODEL NVARCHAR(100),
  IN I_TRADEINYEAR NVARCHAR(10),
  IN I_TRADEINKMS NVARCHAR(50),
  IN I_TRADEINEXPECTEDPRICE NVARCHAR(100),
  IN I_SALESPERSON NVARCHAR(200),
  IN I_SLPCODE NVARCHAR(50),
  IN I_NOTES NCLOB,
  IN I_STATUS NVARCHAR(50),
  IN I_PRIORITY NVARCHAR(20),
  IN I_FOLLOWUPDATE NVARCHAR(50),
  IN I_FOLLOWUPNOTES NCLOB,
  IN I_CREATEDDATE NVARCHAR(50),
  IN I_CREATEDBY NVARCHAR(200)
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
AS
BEGIN
  IF :I_MOBILE IS NULL OR LENGTH(TRIM(:I_MOBILE)) = 0 THEN
    SIGNAL SQL_ERROR_CODE 10001 SET MESSAGE_TEXT = 'MOBILE is required';
  END IF;

  IF :I_CREATEDBY IS NULL OR LENGTH(TRIM(:I_CREATEDBY)) = 0 THEN
    SIGNAL SQL_ERROR_CODE 10002 SET MESSAGE_TEXT = 'CREATEDBY is required';
  END IF;

  IF :I_FINANCING IS NOT NULL AND :I_FINANCING NOT IN ('yes', 'no', 'maybe') THEN
    SIGNAL SQL_ERROR_CODE 10003 SET MESSAGE_TEXT = 'Invalid FINANCING value. Allowed: yes, no, maybe';
  END IF;

  INSERT INTO "BI_NEGT_KSAISUZU"."DMS_SALESENQUIRY" (
    "CUSTOMERID", "CUSTOMERNAME", "ADDRESS", "POSTCODE",
    "HOMEPHONE", "WORKPHONE", "MOBILE", "HOMEEMAIL",
    "MAKE", "MAKENAME", "MODEL", "MODELNAME", "VARIANT", "VARIANTNAME",
    "YEAR", "COLOR", "SUPPCATNUM", "MODELCODE", "QUANTITY", "VINNUMBER", "VINDETAILS",
    "BRANCH", "BRANCHNAME", "BUDGET", "FINANCING",
    "PREFERREDCONTACT", "PREFERREDTIME", "PREFERREDDELIVERY", "SOURCE", "SALESTYPE",
    "TRADEINMAKE", "TRADEINMODEL", "TRADEINYEAR", "TRADEINKMS", "TRADEINEXPECTEDPRICE",
    "SALESPERSON", "SLPCODE", "NOTES",
    "STATUS", "PRIORITY", "FOLLOWUPDATE", "FOLLOWUPNOTES",
    "CREATEDDATE", "CREATEDBY"
  )
  VALUES (
    :I_CUSTOMERID, :I_CUSTOMERNAME, :I_ADDRESS, :I_POSTCODE,
    :I_HOMEPHONE, :I_WORKPHONE, :I_MOBILE, :I_HOMEEMAIL,
    :I_MAKE, :I_MAKENAME, :I_MODEL, :I_MODELNAME, :I_VARIANT, :I_VARIANTNAME,
    :I_YEAR, :I_COLOR, :I_SUPPCATNUM, :I_MODELCODE, COALESCE(:I_QUANTITY, 1), :I_VINNUMBER, :I_VINDETAILS,
    :I_BRANCH, :I_BRANCHNAME, :I_BUDGET, :I_FINANCING,
    :I_PREFERREDCONTACT, :I_PREFERREDTIME, :I_PREFERREDDELIVERY, :I_SOURCE, :I_SALESTYPE,
    :I_TRADEINMAKE, :I_TRADEINMODEL, :I_TRADEINYEAR, :I_TRADEINKMS, :I_TRADEINEXPECTEDPRICE,
    :I_SALESPERSON, :I_SLPCODE, :I_NOTES,
    COALESCE(:I_STATUS, 'Active'), COALESCE(:I_PRIORITY, 'Medium'), :I_FOLLOWUPDATE, :I_FOLLOWUPNOTES,
    :I_CREATEDDATE, :I_CREATEDBY
  );

  SELECT
    CURRENT_IDENTITY_VALUE() AS "SLNO",
    'Sales enquiry created successfully' AS "MESSAGE"
  FROM DUMMY;
END;

-- Permission for integration user:
-- GRANT EXECUTE ON PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100006_EORDER" TO "NETUSR";
