-- Normalize quotation schema so header keeps only document-level fields
-- and VIN / vehicle details live on the line items table.
-- Schema: BI_NEGT_KSAISUZU

-- 1. Add vehicle detail columns to line items if they do not already exist.
ALTER TABLE "BI_NEGT_KSAISUZU"."DMS_QUOTATION_LINE_ITEMS" ADD (
  "VEHICLE_MAKE" NVARCHAR(100),
  "VEHICLE_MODEL" NVARCHAR(100),
  "VEHICLE_VARIANT" NVARCHAR(100),
  "VEHICLE_YEAR" NVARCHAR(10),
  "VEHICLE_COLOR" NVARCHAR(100),
  "VIN_NUMBER" NVARCHAR(100),
  "WHSCODE" NVARCHAR(50)
);

-- 2. Backfill existing line rows from the current quotation header values.
UPDATE "BI_NEGT_KSAISUZU"."DMS_QUOTATION_LINE_ITEMS" L
SET
  "VEHICLE_MAKE" = COALESCE("VEHICLE_MAKE", (
    SELECT H."VEHICLE_MAKE"
    FROM "BI_NEGT_KSAISUZU"."DMS_QUOTATION" H
    WHERE H."SLNO" = L."QUOTATION_SLNO"
  )),
  "VEHICLE_MODEL" = COALESCE("VEHICLE_MODEL", (
    SELECT H."VEHICLE_MODEL"
    FROM "BI_NEGT_KSAISUZU"."DMS_QUOTATION" H
    WHERE H."SLNO" = L."QUOTATION_SLNO"
  )),
  "VEHICLE_VARIANT" = COALESCE("VEHICLE_VARIANT", (
    SELECT H."VEHICLE_VARIANT"
    FROM "BI_NEGT_KSAISUZU"."DMS_QUOTATION" H
    WHERE H."SLNO" = L."QUOTATION_SLNO"
  )),
  "VEHICLE_YEAR" = COALESCE("VEHICLE_YEAR", (
    SELECT H."VEHICLE_YEAR"
    FROM "BI_NEGT_KSAISUZU"."DMS_QUOTATION" H
    WHERE H."SLNO" = L."QUOTATION_SLNO"
  )),
  "VEHICLE_COLOR" = COALESCE("VEHICLE_COLOR", (
    SELECT H."VEHICLE_COLOR"
    FROM "BI_NEGT_KSAISUZU"."DMS_QUOTATION" H
    WHERE H."SLNO" = L."QUOTATION_SLNO"
  )),
  "VIN_NUMBER" = COALESCE("VIN_NUMBER", (
    SELECT H."VIN_NUMBER"
    FROM "BI_NEGT_KSAISUZU"."DMS_QUOTATION" H
    WHERE H."SLNO" = L."QUOTATION_SLNO"
  ));

-- 3. Optional final cleanup once all code paths are deployed and verified.
-- ALTER TABLE "BI_NEGT_KSAISUZU"."DMS_QUOTATION" DROP (
--   "VEHICLE_MAKE",
--   "VEHICLE_MODEL",
--   "VEHICLE_VARIANT",
--   "VEHICLE_YEAR",
--   "VEHICLE_COLOR",
--   "VIN_NUMBER"
-- );
