-- DMS_KSA_CREATE_SALES_ORDER_EORDER: Create Sales Order Header
-- Schema: BI_NEGT_KSAISUZU

-- DROP PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_CREATE_SALES_ORDER_EORDER";
CREATE PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_CREATE_SALES_ORDER_EORDER" (
  IN I_SALES_ORDER_NUMBER NVARCHAR(50),
  IN I_QUOTATION_SLNO INTEGER,
  IN I_ENQUIRY_SLNO INTEGER,
  IN I_CUSTOMER_NAME NVARCHAR(200),
  IN I_CUSTOMER_MOBILE NVARCHAR(50),
  IN I_CUSTOMER_EMAIL NVARCHAR(200),
  IN I_VEHICLE_MAKE NVARCHAR(100),
  IN I_VEHICLE_MODEL NVARCHAR(100),
  IN I_VEHICLE_VARIANT NVARCHAR(100),
  IN I_VIN_NUMBER NVARCHAR(100),
  IN I_GRAND_TOTAL DECIMAL(19, 6),
  IN I_NOTES NCLOB,
  IN I_SLPCODE NVARCHAR(50),
  IN I_CREATED_BY NVARCHAR(100),
  IN I_CREATED_DATE NVARCHAR(19)
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
AS
BEGIN
  DECLARE V_SLNO INTEGER;

  SELECT COALESCE(MAX("SLNO"), 0) + 1 INTO V_SLNO
  FROM "BI_NEGT_KSAISUZU"."DMS_SALES_ORDER";

  INSERT INTO "BI_NEGT_KSAISUZU"."DMS_SALES_ORDER" (
    "SLNO",
    "SALES_ORDER_NUMBER", "QUOTATION_SLNO", "ENQUIRY_SLNO",
    "VERSION", "IS_LATEST_VERSION",
    "CUSTOMER_NAME", "CUSTOMER_MOBILE", "CUSTOMER_EMAIL",
    "VEHICLE_MAKE", "VEHICLE_MODEL", "VEHICLE_VARIANT", "VIN_NUMBER",
    "GRAND_TOTAL", "STATUS", "NOTES", "SLPCODE",
    "CREATED_BY", "CREATED_DATE", "IS_DELETED"
  ) VALUES (
    :V_SLNO,
    :I_SALES_ORDER_NUMBER, :I_QUOTATION_SLNO, :I_ENQUIRY_SLNO,
    1, 'Y',
    :I_CUSTOMER_NAME, :I_CUSTOMER_MOBILE, :I_CUSTOMER_EMAIL,
    :I_VEHICLE_MAKE, :I_VEHICLE_MODEL, :I_VEHICLE_VARIANT, :I_VIN_NUMBER,
    :I_GRAND_TOTAL, 'Provisional', :I_NOTES, :I_SLPCODE,
    :I_CREATED_BY, TO_TIMESTAMP(:I_CREATED_DATE, 'YYYY-MM-DD HH24:MI:SS'), 'N'
  );
END;

-- Optional grant
-- GRANT EXECUTE ON PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_CREATE_SALES_ORDER_EORDER" TO "NETUSR";
