-- Add customer code to quotation header and backfill from enquiry.
-- Schema: BI_NEGT_KSAISUZU

ALTER TABLE "BI_NEGT_KSAISUZU"."DMS_QUOTATION" ADD (
  "CUSTOMER_CODE" NVARCHAR(50)
);

UPDATE "BI_NEGT_KSAISUZU"."DMS_QUOTATION" Q
SET "CUSTOMER_CODE" = COALESCE("CUSTOMER_CODE", (
  SELECT E."CUSTOMERID"
  FROM "BI_NEGT_KSAISUZU"."DMS_SALESENQUIRY" E
  WHERE E."SLNO" = Q."ENQUIRY_SLNO"
))
WHERE "CUSTOMER_CODE" IS NULL;
