-- DMS_KSA_100017_EORDER: Create Quotation Header
-- DMS_KSA_100018_EORDER: Create Quotation Line Item
-- Schema: BI_NEGT_KSAISUZU

-- DROP PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100017_EORDER";
CREATE PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100017_EORDER" (
  IN I_ENQUIRY_SLNO INTEGER,
  IN I_QUOTATION_NUMBER NVARCHAR(50),
  IN I_DOC_TYPE NVARCHAR(2),
  IN I_SOURCE_QUOTATION_SLNO INTEGER,
  IN I_CUSTOMER_CODE NVARCHAR(50),
  IN I_CUSTOMER_NAME NVARCHAR(200),
  IN I_CUSTOMER_MOBILE NVARCHAR(50),
  IN I_CUSTOMER_EMAIL NVARCHAR(200),
  IN I_CUSTOMER_ADDRESS NVARCHAR(500),
  IN I_VEHICLE_BASE_PRICE DECIMAL(19, 6),
  IN I_VEHICLE_DISCOUNT DECIMAL(19, 6),
  IN I_VEHICLE_NET_PRICE DECIMAL(19, 6),
  IN I_ACCESSORIES_TOTAL DECIMAL(19, 6),
  IN I_ACCESSORIES_DISCOUNT DECIMAL(19, 6),
  IN I_ACCESSORIES_NET_TOTAL DECIMAL(19, 6),
  IN I_WARRANTY_TOTAL DECIMAL(19, 6),
  IN I_INSURANCE_TOTAL DECIMAL(19, 6),
  IN I_SUBTOTAL DECIMAL(19, 6),
  IN I_TAX_RATE DECIMAL(9, 4),
  IN I_TAX_AMOUNT DECIMAL(19, 6),
  IN I_GRAND_TOTAL DECIMAL(19, 6),
  IN I_TRADE_IN_VALUE DECIMAL(19, 6),
  IN I_TRADE_IN_APPRAISAL_SLNO INTEGER,
  IN I_FINANCING_SCHEME_SLNO INTEGER,
  IN I_DOWNPAYMENT DECIMAL(19, 6),
  IN I_NET_AMOUNT_DUE DECIMAL(19, 6),
  IN I_TOTAL_DISCOUNT_AMOUNT DECIMAL(19, 6),
  IN I_DISCOUNT_PERCENTAGE DECIMAL(9, 4),
  IN I_REQUIRES_APPROVAL NVARCHAR(1),
  IN I_DISCOUNT_APPROVAL_STATUS NVARCHAR(20),
  IN I_STATUS NVARCHAR(20),
  IN I_VALID_UNTIL NVARCHAR(30),
  IN I_NOTES NCLOB,
  IN I_TERMS_AND_CONDITIONS NCLOB,
  IN I_INTERNAL_NOTES NCLOB,
  IN I_SALESPERSON NVARCHAR(100),
  IN I_SLPCODE NVARCHAR(50),
  IN I_BRANCH NVARCHAR(100),
  IN I_CREATED_BY NVARCHAR(100),
  IN I_CREATED_DATE NVARCHAR(19)
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
AS
BEGIN
  DECLARE V_SLNO INTEGER;
  SELECT COALESCE(MAX("SLNO"), 0) + 1 INTO V_SLNO
  FROM "BI_NEGT_KSAISUZU"."DMS_QUOTATION";

  INSERT INTO "BI_NEGT_KSAISUZU"."DMS_QUOTATION" (
    "SLNO",
    "DOC_TYPE", "SOURCE_QUOTATION_SLNO",
    "ENQUIRY_SLNO", "QUOTATION_NUMBER", "VERSION", "IS_LATEST_VERSION",
    "CUSTOMER_CODE", "CUSTOMER_NAME", "CUSTOMER_MOBILE", "CUSTOMER_EMAIL", "CUSTOMER_ADDRESS",
    "VEHICLE_BASE_PRICE", "VEHICLE_DISCOUNT", "VEHICLE_NET_PRICE",
    "ACCESSORIES_TOTAL", "ACCESSORIES_DISCOUNT", "ACCESSORIES_NET_TOTAL",
    "WARRANTY_TOTAL", "INSURANCE_TOTAL",
    "SUBTOTAL", "TAX_RATE", "TAX_AMOUNT", "GRAND_TOTAL",
    "TRADE_IN_VALUE", "TRADE_IN_APPRAISAL_SLNO", "FINANCING_SCHEME_SLNO",
    "DOWNPAYMENT", "NET_AMOUNT_DUE",
    "TOTAL_DISCOUNT_AMOUNT", "DISCOUNT_PERCENTAGE",
    "REQUIRES_APPROVAL", "DISCOUNT_APPROVAL_STATUS",
    "STATUS", "VALID_UNTIL", "NOTES", "TERMS_AND_CONDITIONS", "INTERNAL_NOTES",
    "SALESPERSON", "SLPCODE", "BRANCH",
    "CREATED_BY", "CREATED_DATE", "IS_DELETED"
  ) VALUES (
    :V_SLNO,
    COALESCE(NULLIF(:I_DOC_TYPE, ''), 'SQ'), :I_SOURCE_QUOTATION_SLNO,
    :I_ENQUIRY_SLNO, :I_QUOTATION_NUMBER, 1, 'Y',
    :I_CUSTOMER_CODE, :I_CUSTOMER_NAME, :I_CUSTOMER_MOBILE, :I_CUSTOMER_EMAIL, :I_CUSTOMER_ADDRESS,
    :I_VEHICLE_BASE_PRICE, :I_VEHICLE_DISCOUNT, :I_VEHICLE_NET_PRICE,
    :I_ACCESSORIES_TOTAL, :I_ACCESSORIES_DISCOUNT, :I_ACCESSORIES_NET_TOTAL,
    :I_WARRANTY_TOTAL, :I_INSURANCE_TOTAL,
    :I_SUBTOTAL, :I_TAX_RATE, :I_TAX_AMOUNT, :I_GRAND_TOTAL,
    :I_TRADE_IN_VALUE, :I_TRADE_IN_APPRAISAL_SLNO, :I_FINANCING_SCHEME_SLNO,
    :I_DOWNPAYMENT, :I_NET_AMOUNT_DUE,
    :I_TOTAL_DISCOUNT_AMOUNT, :I_DISCOUNT_PERCENTAGE,
    :I_REQUIRES_APPROVAL, :I_DISCOUNT_APPROVAL_STATUS,
    :I_STATUS, :I_VALID_UNTIL, :I_NOTES, :I_TERMS_AND_CONDITIONS, :I_INTERNAL_NOTES,
    :I_SALESPERSON, :I_SLPCODE, :I_BRANCH,
    :I_CREATED_BY, TO_TIMESTAMP(:I_CREATED_DATE, 'YYYY-MM-DD HH24:MI:SS'), 'N'
  );
END;

-- DROP PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100018_EORDER";
CREATE PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100018_EORDER" (
  IN I_QUOTATION_SLNO INTEGER,
  IN I_LINE_NUMBER INTEGER,
  IN I_ITEM_TYPE NVARCHAR(20),
  IN I_ITEM_CODE NVARCHAR(100),
  IN I_ITEM_DESCRIPTION NVARCHAR(500),
  IN I_ITEM_CATEGORY NVARCHAR(100),
  IN I_QUANTITY INTEGER,
  IN I_UNIT_PRICE DECIMAL(19, 6),
  IN I_DISCOUNT_AMOUNT DECIMAL(19, 6),
  IN I_DISCOUNT_PERCENTAGE DECIMAL(9, 4),
  IN I_NET_PRICE DECIMAL(19, 6),
  IN I_TAX_INCLUDED NVARCHAR(1),
  IN I_VEHICLE_MAKE NVARCHAR(100),
  IN I_VEHICLE_MODEL NVARCHAR(100),
  IN I_VEHICLE_VARIANT NVARCHAR(100),
  IN I_VEHICLE_YEAR NVARCHAR(10),
  IN I_VEHICLE_COLOR NVARCHAR(100),
  IN I_VIN_NUMBER NVARCHAR(100),
  IN I_WHSCODE NVARCHAR(50),
  IN I_MANUFACTURER NVARCHAR(100),
  IN I_PART_NUMBER NVARCHAR(100),
  IN I_WARRANTY_PERIOD NVARCHAR(50),
  IN I_NOTES NCLOB,
  IN I_CREATED_BY NVARCHAR(100),
  IN I_CREATED_DATE NVARCHAR(19)
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
AS
BEGIN
  DECLARE V_SLNO INTEGER;
  SELECT COALESCE(MAX("SLNO"), 0) + 1 INTO V_SLNO
  FROM "BI_NEGT_KSAISUZU"."DMS_QUOTATION_LINE_ITEMS";

  INSERT INTO "BI_NEGT_KSAISUZU"."DMS_QUOTATION_LINE_ITEMS" (
    "SLNO",
    "QUOTATION_SLNO", "LINE_NUMBER", "ITEM_TYPE", "ITEM_CODE",
    "ITEM_DESCRIPTION", "ITEM_CATEGORY", "QUANTITY", "UNIT_PRICE",
    "DISCOUNT_AMOUNT", "DISCOUNT_PERCENTAGE", "NET_PRICE", "TAX_INCLUDED",
    "VEHICLE_MAKE", "VEHICLE_MODEL", "VEHICLE_VARIANT", "VEHICLE_YEAR",
    "VEHICLE_COLOR", "VIN_NUMBER", "WHSCODE",
    "MANUFACTURER", "PART_NUMBER", "WARRANTY_PERIOD", "NOTES",
    "CREATED_BY", "CREATED_DATE", "IS_DELETED"
  ) VALUES (
    :V_SLNO,
    :I_QUOTATION_SLNO, :I_LINE_NUMBER, :I_ITEM_TYPE, :I_ITEM_CODE,
    :I_ITEM_DESCRIPTION, :I_ITEM_CATEGORY, :I_QUANTITY, :I_UNIT_PRICE,
    :I_DISCOUNT_AMOUNT, :I_DISCOUNT_PERCENTAGE, :I_NET_PRICE, :I_TAX_INCLUDED,
    :I_VEHICLE_MAKE, :I_VEHICLE_MODEL, :I_VEHICLE_VARIANT, :I_VEHICLE_YEAR,
    :I_VEHICLE_COLOR, :I_VIN_NUMBER, :I_WHSCODE,
    :I_MANUFACTURER, :I_PART_NUMBER, :I_WARRANTY_PERIOD, :I_NOTES,
    :I_CREATED_BY, TO_TIMESTAMP(:I_CREATED_DATE, 'YYYY-MM-DD HH24:MI:SS'), 'N'
  );
END;

-- Optional grants
-- GRANT EXECUTE ON PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100017_EORDER" TO "NETUSR";
-- GRANT EXECUTE ON PROCEDURE "BI_NEGT_KSAISUZU"."DMS_KSA_100018_EORDER" TO "NETUSR";
