-- Add API / SAP reference fields to quotation header.
-- Schema: BI_NEGT_KSAISUZU

ALTER TABLE "BI_NEGT_KSAISUZU"."DMS_QUOTATION" ADD (
  "APILOG" NCLOB,
  "SAPDOCNUM" NVARCHAR(120),
  "SAPDOCENTRY" NVARCHAR(120)
);

-- Optional backfill from the latest quotation integration log, if available.
UPDATE "BI_NEGT_KSAISUZU"."DMS_QUOTATION" Q
SET
  "APILOG" = COALESCE("APILOG", (
    SELECT COALESCE(L."QUEUE_RESPONSE", L."SUBMIT_RESPONSE", L."ERROR_MESSAGE")
    FROM "BI_NEGT_KSAISUZU"."DMS_SO_SQ_INTEGRATION_LOG" L
    WHERE L."SOURCE_TYPE" = 'Quotation'
      AND L."SOURCE_SLNO" = Q."SLNO"
      AND COALESCE(L."IS_DELETED", 'N') = 'N'
    ORDER BY L."SLNO" DESC
    LIMIT 1
  )),
  "SAPDOCENTRY" = COALESCE("SAPDOCENTRY", (
    SELECT L."SAP_DOCENTRY"
    FROM "BI_NEGT_KSAISUZU"."DMS_SO_SQ_INTEGRATION_LOG" L
    WHERE L."SOURCE_TYPE" = 'Quotation'
      AND L."SOURCE_SLNO" = Q."SLNO"
      AND COALESCE(L."IS_DELETED", 'N') = 'N'
    ORDER BY L."SLNO" DESC
    LIMIT 1
  )),
  "SAPDOCNUM" = COALESCE("SAPDOCNUM", (
    SELECT CASE
      WHEN COALESCE(L."REFERENCE_SOURCE", '') = 'docEntry' THEN L."REFERENCE_NUMBER"
      ELSE NULL
    END
    FROM "BI_NEGT_KSAISUZU"."DMS_SO_SQ_INTEGRATION_LOG" L
    WHERE L."SOURCE_TYPE" = 'Quotation'
      AND L."SOURCE_SLNO" = Q."SLNO"
      AND COALESCE(L."IS_DELETED", 'N') = 'N'
    ORDER BY L."SLNO" DESC
    LIMIT 1
  ));
