-- Unify sales orders into DMS_QUOTATION / DMS_QUOTATION_LINE_ITEMS.
-- Schema: BI_NEGT_KSAISUZU
--
-- This migration:
-- 1. Adds DOC_TYPE and SOURCE_QUOTATION_SLNO to DMS_QUOTATION
-- 2. Adds sales-order workflow columns to DMS_QUOTATION
-- 3. Marks existing quotations as DOC_TYPE = 'SQ'
-- 4. Optionally backfills existing DMS_SALES_ORDER rows into DMS_QUOTATION
--    and clones quotation line items into new sales-order-owned line rows

ALTER TABLE "BI_NEGT_KSAISUZU"."DMS_QUOTATION" ADD (
  "DOC_TYPE" NVARCHAR(2),
  "SOURCE_QUOTATION_SLNO" INTEGER,
  "PRINTED_BY" NVARCHAR(100),
  "PRINTED_DATE" TIMESTAMP,
  "PASSED_TO_VEHICLE_ADMIN" NVARCHAR(1),
  "PASSED_TO_VA_DATE" TIMESTAMP,
  "PASSED_TO_VA_BY" NVARCHAR(100),
  "VEHICLE_ADMIN_ASSIGNED_TO" NVARCHAR(100),
  "VEHICLE_ADMIN_NOTES" NCLOB,
  "HANDOVER_BOOKED" NVARCHAR(1),
  "HANDOVER_DATE" NVARCHAR(30),
  "HANDOVER_TIME" NVARCHAR(30),
  "HANDOVER_LOCATION" NVARCHAR(255),
  "HANDOVER_NOTES" NCLOB,
  "HANDOVER_BOOKED_BY" NVARCHAR(100),
  "HANDOVER_BOOKED_DATE" TIMESTAMP,
  "IS_LOST_SALE" NVARCHAR(1),
  "LOST_SALE_DATE" TIMESTAMP,
  "LOST_REASON" NCLOB,
  "LOST_NOTES" NCLOB,
  "CANCELLATION_REASON" NCLOB,
  "CANCELLED_DATE" TIMESTAMP,
  "CANCELLED_BY" NVARCHAR(100)
);

UPDATE "BI_NEGT_KSAISUZU"."DMS_QUOTATION"
SET "DOC_TYPE" = 'SQ'
WHERE "DOC_TYPE" IS NULL OR TRIM("DOC_TYPE") = '';

DO
BEGIN
  DECLARE V_BASE_QUOTATION_SLNO INTEGER;
  DECLARE V_BASE_LINE_SLNO INTEGER;

  SELECT COALESCE(MAX("SLNO"), 0) INTO V_BASE_QUOTATION_SLNO
  FROM "BI_NEGT_KSAISUZU"."DMS_QUOTATION";

  INSERT INTO "BI_NEGT_KSAISUZU"."DMS_QUOTATION" (
    "SLNO",
    "DOC_TYPE",
    "SOURCE_QUOTATION_SLNO",
    "ENQUIRY_SLNO",
    "QUOTATION_NUMBER",
    "VERSION",
    "PARENT_QUOTATION_SLNO",
    "IS_LATEST_VERSION",
    "CUSTOMER_CODE",
    "CUSTOMER_NAME",
    "CUSTOMER_MOBILE",
    "CUSTOMER_EMAIL",
    "CUSTOMER_ADDRESS",
    "VEHICLE_BASE_PRICE",
    "VEHICLE_DISCOUNT",
    "VEHICLE_NET_PRICE",
    "ACCESSORIES_TOTAL",
    "ACCESSORIES_DISCOUNT",
    "ACCESSORIES_NET_TOTAL",
    "WARRANTY_TOTAL",
    "INSURANCE_TOTAL",
    "SUBTOTAL",
    "TAX_RATE",
    "TAX_AMOUNT",
    "GRAND_TOTAL",
    "TRADE_IN_VALUE",
    "TRADE_IN_APPRAISAL_SLNO",
    "FINANCING_SCHEME_SLNO",
    "DOWNPAYMENT",
    "NET_AMOUNT_DUE",
    "TOTAL_DISCOUNT_AMOUNT",
    "DISCOUNT_PERCENTAGE",
    "REQUIRES_APPROVAL",
    "DISCOUNT_APPROVAL_STATUS",
    "STATUS",
    "VALID_UNTIL",
    "NOTES",
    "TERMS_AND_CONDITIONS",
    "INTERNAL_NOTES",
    "PASSED_TO_CASHIER",
    "PASSED_TO_CASHIER_DATE",
    "PASSED_TO_CASHIER_BY",
    "DEPOSIT_AMOUNT",
    "DEPOSIT_COLLECTED",
    "VEHICLE_RESERVED",
    "VEHICLE_RESERVED_DATE",
    "VEHICLE_RESERVED_BY",
    "VEHICLE_RESERVATION_NOTES",
    "HANDOVER_BOOKED",
    "HANDOVER_DATE",
    "HANDOVER_TIME",
    "HANDOVER_LOCATION",
    "HANDOVER_NOTES",
    "HANDOVER_BOOKED_BY",
    "HANDOVER_BOOKED_DATE",
    "PRINTED_BY",
    "PRINTED_DATE",
    "PASSED_TO_VEHICLE_ADMIN",
    "PASSED_TO_VA_DATE",
    "PASSED_TO_VA_BY",
    "VEHICLE_ADMIN_ASSIGNED_TO",
    "VEHICLE_ADMIN_NOTES",
    "IS_LOST_SALE",
    "LOST_SALE_DATE",
    "LOST_REASON",
    "LOST_NOTES",
    "CANCELLATION_REASON",
    "CANCELLED_DATE",
    "CANCELLED_BY",
    "SLPCODE",
    "CREATED_BY",
    "CREATED_DATE",
    "UPDATED_BY",
    "UPDATED_DATE",
    "IS_DELETED"
  )
  SELECT
    V_BASE_QUOTATION_SLNO + ROW_NUMBER() OVER (ORDER BY SO."SLNO") AS "SLNO",
    'SO' AS "DOC_TYPE",
    SO."QUOTATION_SLNO" AS "SOURCE_QUOTATION_SLNO",
    SO."ENQUIRY_SLNO",
    SO."SALES_ORDER_NUMBER" AS "QUOTATION_NUMBER",
    COALESCE(SO."VERSION", 1) AS "VERSION",
    SO."PARENT_ORDER_SLNO" AS "PARENT_QUOTATION_SLNO",
    COALESCE(SO."IS_LATEST_VERSION", 'Y') AS "IS_LATEST_VERSION",
    NULL AS "CUSTOMER_CODE",
    SO."CUSTOMER_NAME",
    SO."CUSTOMER_MOBILE",
    SO."CUSTOMER_EMAIL",
    NULL AS "CUSTOMER_ADDRESS",
    COALESCE(SO."GRAND_TOTAL", 0) AS "VEHICLE_BASE_PRICE",
    0 AS "VEHICLE_DISCOUNT",
    COALESCE(SO."GRAND_TOTAL", 0) AS "VEHICLE_NET_PRICE",
    0 AS "ACCESSORIES_TOTAL",
    0 AS "ACCESSORIES_DISCOUNT",
    0 AS "ACCESSORIES_NET_TOTAL",
    0 AS "WARRANTY_TOTAL",
    0 AS "INSURANCE_TOTAL",
    COALESCE(SO."GRAND_TOTAL", 0) AS "SUBTOTAL",
    0 AS "TAX_RATE",
    0 AS "TAX_AMOUNT",
    COALESCE(SO."GRAND_TOTAL", 0) AS "GRAND_TOTAL",
    0 AS "TRADE_IN_VALUE",
    NULL AS "TRADE_IN_APPRAISAL_SLNO",
    NULL AS "FINANCING_SCHEME_SLNO",
    0 AS "DOWNPAYMENT",
    COALESCE(SO."GRAND_TOTAL", 0) AS "NET_AMOUNT_DUE",
    0 AS "TOTAL_DISCOUNT_AMOUNT",
    0 AS "DISCOUNT_PERCENTAGE",
    'N' AS "REQUIRES_APPROVAL",
    NULL AS "DISCOUNT_APPROVAL_STATUS",
    SO."STATUS",
    NULL AS "VALID_UNTIL",
    SO."NOTES",
    NULL AS "TERMS_AND_CONDITIONS",
    NULL AS "INTERNAL_NOTES",
    'N' AS "PASSED_TO_CASHIER",
    NULL AS "PASSED_TO_CASHIER_DATE",
    NULL AS "PASSED_TO_CASHIER_BY",
    0 AS "DEPOSIT_AMOUNT",
    'N' AS "DEPOSIT_COLLECTED",
    SO."VEHICLE_RESERVED",
    SO."VEHICLE_RESERVED_DATE",
    SO."VEHICLE_RESERVED_BY",
    SO."VEHICLE_RESERVATION_NOTES",
    SO."HANDOVER_BOOKED",
    SO."HANDOVER_DATE",
    SO."HANDOVER_TIME",
    SO."HANDOVER_LOCATION",
    SO."HANDOVER_NOTES",
    SO."HANDOVER_BOOKED_BY",
    SO."HANDOVER_BOOKED_DATE",
    SO."PRINTED_BY",
    SO."PRINTED_DATE",
    SO."PASSED_TO_VEHICLE_ADMIN",
    SO."PASSED_TO_VA_DATE",
    SO."PASSED_TO_VA_BY",
    SO."VEHICLE_ADMIN_ASSIGNED_TO",
    SO."VEHICLE_ADMIN_NOTES",
    SO."IS_LOST_SALE",
    SO."LOST_SALE_DATE",
    SO."LOST_REASON",
    SO."LOST_NOTES",
    SO."CANCELLATION_REASON",
    SO."CANCELLED_DATE",
    SO."CANCELLED_BY",
    SO."SLPCODE",
    SO."CREATED_BY",
    SO."CREATED_DATE",
    SO."UPDATED_BY",
    SO."UPDATED_DATE",
    COALESCE(SO."IS_DELETED", 'N') AS "IS_DELETED"
  FROM "BI_NEGT_KSAISUZU"."DMS_SALES_ORDER" SO
  LEFT JOIN "BI_NEGT_KSAISUZU"."DMS_QUOTATION" TARGET
    ON TARGET."DOC_TYPE" = 'SO'
   AND TARGET."QUOTATION_NUMBER" = SO."SALES_ORDER_NUMBER"
  WHERE TARGET."SLNO" IS NULL;

  SELECT COALESCE(MAX("SLNO"), 0) INTO V_BASE_LINE_SLNO
  FROM "BI_NEGT_KSAISUZU"."DMS_QUOTATION_LINE_ITEMS";

  INSERT INTO "BI_NEGT_KSAISUZU"."DMS_QUOTATION_LINE_ITEMS" (
    "SLNO",
    "QUOTATION_SLNO",
    "LINE_NUMBER",
    "ITEM_TYPE",
    "ITEM_CODE",
    "ITEM_DESCRIPTION",
    "ITEM_CATEGORY",
    "QUANTITY",
    "UNIT_PRICE",
    "DISCOUNT_AMOUNT",
    "DISCOUNT_PERCENTAGE",
    "NET_PRICE",
    "TAX_INCLUDED",
    "VEHICLE_MAKE",
    "VEHICLE_MODEL",
    "VEHICLE_VARIANT",
    "VEHICLE_YEAR",
    "VEHICLE_COLOR",
    "VIN_NUMBER",
    "WHSCODE",
    "MANUFACTURER",
    "PART_NUMBER",
    "WARRANTY_PERIOD",
    "NOTES",
    "CREATED_BY",
    "CREATED_DATE",
    "UPDATED_BY",
    "UPDATED_DATE",
    "IS_DELETED"
  )
  SELECT
    V_BASE_LINE_SLNO + ROW_NUMBER() OVER (ORDER BY TARGET."SLNO", LI."LINE_NUMBER", LI."SLNO") AS "SLNO",
    TARGET."SLNO" AS "QUOTATION_SLNO",
    LI."LINE_NUMBER",
    LI."ITEM_TYPE",
    LI."ITEM_CODE",
    LI."ITEM_DESCRIPTION",
    LI."ITEM_CATEGORY",
    LI."QUANTITY",
    LI."UNIT_PRICE",
    LI."DISCOUNT_AMOUNT",
    LI."DISCOUNT_PERCENTAGE",
    LI."NET_PRICE",
    LI."TAX_INCLUDED",
    LI."VEHICLE_MAKE",
    LI."VEHICLE_MODEL",
    LI."VEHICLE_VARIANT",
    LI."VEHICLE_YEAR",
    LI."VEHICLE_COLOR",
    LI."VIN_NUMBER",
    LI."WHSCODE",
    LI."MANUFACTURER",
    LI."PART_NUMBER",
    LI."WARRANTY_PERIOD",
    LI."NOTES",
    LI."CREATED_BY",
    LI."CREATED_DATE",
    LI."UPDATED_BY",
    LI."UPDATED_DATE",
    COALESCE(LI."IS_DELETED", 'N') AS "IS_DELETED"
  FROM "BI_NEGT_KSAISUZU"."DMS_SALES_ORDER" SO
  INNER JOIN "BI_NEGT_KSAISUZU"."DMS_QUOTATION" TARGET
    ON TARGET."DOC_TYPE" = 'SO'
   AND TARGET."QUOTATION_NUMBER" = SO."SALES_ORDER_NUMBER"
  INNER JOIN "BI_NEGT_KSAISUZU"."DMS_QUOTATION_LINE_ITEMS" LI
    ON LI."QUOTATION_SLNO" = SO."QUOTATION_SLNO"
   AND LI."IS_DELETED" = 'N'
  LEFT JOIN "BI_NEGT_KSAISUZU"."DMS_QUOTATION_LINE_ITEMS" EXISTING_LI
    ON EXISTING_LI."QUOTATION_SLNO" = TARGET."SLNO"
   AND EXISTING_LI."IS_DELETED" = 'N'
  WHERE EXISTING_LI."SLNO" IS NULL;
END;
