-- Create linked charges table for sales enquiries
-- Schema: BI_NEGT_KSAISUZU

CREATE COLUMN TABLE "BI_NEGT_KSAISUZU"."DMS_SALESENQUIRY_CHARGES" (
  "SLNO" INTEGER NOT NULL,
  "ENQUIRY_SLNO" INTEGER NOT NULL,
  "CHARGECODE" NVARCHAR(100),
  "CHARGENAME" NVARCHAR(255),
  "CHARGEPRICE" NVARCHAR(100),
  "CHARGEDETAILS" NCLOB,
  "CREATEDDATE" TIMESTAMP,
  "CREATEDBY" NVARCHAR(200),
  "UPDATEDDATE" TIMESTAMP,
  "UPDATEDBY" NVARCHAR(200),
  "IS_DELETED" NVARCHAR(1) DEFAULT 'N',
  PRIMARY KEY ("SLNO")
);

CREATE INDEX "IDX_DMS_SALESENQUIRY_CHARGES_ENQUIRY"
  ON "BI_NEGT_KSAISUZU"."DMS_SALESENQUIRY_CHARGES" ("ENQUIRY_SLNO");
