-- DMS Sales Enquiry Table
-- This table stores sales enquiries for the automotive dealership
-- Schema: BI_NEGT_KSA

CREATE COLUMN TABLE "BI_NEGT_KSA"."DMS_SALESENQUIRY" (
    -- Primary Key
    "SLNO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- Customer Information
    "CUSTOMERID" NVARCHAR(50),
    "CUSTOMERNAME" NVARCHAR(200),
    "ADDRESS" NVARCHAR(500),
    "POSTCODE" NVARCHAR(20),
    "HOMEPHONE" NVARCHAR(50),
    "WORKPHONE" NVARCHAR(50),
    "MOBILE" NVARCHAR(50) NOT NULL,
    "HOMEEMAIL" NVARCHAR(200),

    -- Vehicle Details
    "MAKE" NVARCHAR(100),
    "MAKENAME" NVARCHAR(200),
    "MODEL" NVARCHAR(100),
    "MODELNAME" NVARCHAR(200),
    "VARIANT" NVARCHAR(100),
    "VARIANTNAME" NVARCHAR(200),
    "YEAR" NVARCHAR(10),
    "COLOR" NVARCHAR(100),
    "SUPPCATNUM" NVARCHAR(100),
    "MODELCODE" NVARCHAR(100),
    "QUANTITY" INTEGER DEFAULT 1,
    "VINNUMBER" NVARCHAR(100),
    "VINDETAILS" NCLOB, -- JSON string of VIN details

    -- Enquiry Details
    "BRANCH" NVARCHAR(100),
    "BRANCHNAME" NVARCHAR(200),
    "BUDGET" NVARCHAR(100),
    "FINANCING" NVARCHAR(20), -- 'yes', 'no', 'maybe'
    "PREFERREDCONTACT" NVARCHAR(50), -- 'phone', 'email', 'whatsapp', 'sms'
    "PREFERREDTIME" NVARCHAR(50), -- 'morning', 'afternoon', 'evening', 'anytime'
    "PREFERREDDELIVERY" NVARCHAR(200),
    "SOURCE" NVARCHAR(100), -- Lead source
    "SALESTYPE" NVARCHAR(50), -- Sales type

    -- Trade-in Vehicle
    "TRADEINMAKE" NVARCHAR(100),
    "TRADEINMODEL" NVARCHAR(100),
    "TRADEINYEAR" NVARCHAR(10),
    "TRADEINKMS" NVARCHAR(50),
    "TRADEINEXPECTEDPRICE" NVARCHAR(100),

    -- Additional Information
    "SALESPERSON" NVARCHAR(200),
    "SLPCODE" NVARCHAR(50),
    "NOTES" NCLOB,

    -- Status & Tracking
    "STATUS" NVARCHAR(50) DEFAULT 'Active', -- 'Active', 'Contacted', 'Qualified', 'Converted', 'Lost', 'Closed'
    "PRIORITY" NVARCHAR(20) DEFAULT 'Medium', -- 'Low', 'Medium', 'High'
    "FOLLOWUPDATE" NVARCHAR(50),
    "FOLLOWUPNOTES" NCLOB,

    -- Audit Fields
    "CREATEDDATE" NVARCHAR(50) NOT NULL,
    "CREATEDBY" NVARCHAR(200) NOT NULL,
    "UPDATEDDATE" NVARCHAR(50),
    "UPDATEDBY" NVARCHAR(200)
);

-- Create indexes for better query performance
CREATE INDEX "IDX_SALESENQUIRY_CUSTOMER" ON "BI_NEGT_KSA"."DMS_SALESENQUIRY" ("CUSTOMERID");
CREATE INDEX "IDX_SALESENQUIRY_STATUS" ON "BI_NEGT_KSA"."DMS_SALESENQUIRY" ("STATUS");
CREATE INDEX "IDX_SALESENQUIRY_SALESPERSON" ON "BI_NEGT_KSA"."DMS_SALESENQUIRY" ("SLPCODE");
CREATE INDEX "IDX_SALESENQUIRY_CREATED" ON "BI_NEGT_KSA"."DMS_SALESENQUIRY" ("CREATEDDATE");
