-- Add vehicle reservation columns to quotation table
-- Schema: BI_NEGT_KSAISUZU

ALTER TABLE "BI_NEGT_KSAISUZU"."DMS_QUOTATION"
ADD (
  "VEHICLE_RESERVED" NVARCHAR(1) DEFAULT 'N',
  "VEHICLE_RESERVED_DATE" TIMESTAMP NULL,
  "VEHICLE_RESERVED_BY" NVARCHAR(100) NULL,
  "VEHICLE_RESERVATION_NOTES" NCLOB NULL
);
