-- =====================================================
-- Sales Order Table Migration
-- =====================================================
-- Description: Creates DMS_SALES_ORDER table used for sales-order workflows
-- Date: 2026-03-06
-- =====================================================

CREATE TABLE "BI_NEGT_KSA"."DMS_SALES_ORDER" (
  "SLNO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "SALES_ORDER_NUMBER" NVARCHAR(50) UNIQUE NOT NULL,

  -- References
  "QUOTATION_SLNO" INTEGER NOT NULL,
  "ENQUIRY_SLNO" INTEGER NOT NULL,

  -- Versioning
  "VERSION" INTEGER DEFAULT 1 NOT NULL,
  "PARENT_ORDER_SLNO" INTEGER,
  "IS_LATEST_VERSION" NVARCHAR(1) DEFAULT 'Y' NOT NULL,

  -- Snapshot Data
  "CUSTOMER_NAME" NVARCHAR(200),
  "CUSTOMER_MOBILE" NVARCHAR(50),
  "CUSTOMER_EMAIL" NVARCHAR(200),
  "VEHICLE_MAKE" NVARCHAR(100),
  "VEHICLE_MODEL" NVARCHAR(100),
  "VEHICLE_VARIANT" NVARCHAR(100),
  "VIN_NUMBER" NVARCHAR(100),
  "GRAND_TOTAL" DECIMAL(18,2) DEFAULT 0 NOT NULL,

  -- Workflow
  "STATUS" NVARCHAR(30) DEFAULT 'Provisional' NOT NULL,
  "NOTES" NCLOB,
  "VEHICLE_RESERVED" NVARCHAR(1) DEFAULT 'N',
  "VEHICLE_RESERVED_DATE" NVARCHAR(30),
  "VEHICLE_RESERVED_BY" NVARCHAR(100),
  "VEHICLE_RESERVATION_NOTES" NCLOB,

  -- Ownership & Audit
  "SLPCODE" NVARCHAR(50) NOT NULL,
  "CREATED_BY" NVARCHAR(100) NOT NULL,
  "CREATED_DATE" NVARCHAR(30) NOT NULL,
  "UPDATED_BY" NVARCHAR(100),
  "UPDATED_DATE" NVARCHAR(30),
  "IS_DELETED" NVARCHAR(1) DEFAULT 'N'
);

CREATE INDEX "IDX_SALES_ORDER_NUMBER" ON "BI_NEGT_KSA"."DMS_SALES_ORDER"("SALES_ORDER_NUMBER");
CREATE INDEX "IDX_SALES_ORDER_STATUS" ON "BI_NEGT_KSA"."DMS_SALES_ORDER"("STATUS");
CREATE INDEX "IDX_SALES_ORDER_QUOTATION" ON "BI_NEGT_KSA"."DMS_SALES_ORDER"("QUOTATION_SLNO");
CREATE INDEX "IDX_SALES_ORDER_ENQUIRY" ON "BI_NEGT_KSA"."DMS_SALES_ORDER"("ENQUIRY_SLNO");
CREATE INDEX "IDX_SALES_ORDER_SLPCODE" ON "BI_NEGT_KSA"."DMS_SALES_ORDER"("SLPCODE");
CREATE INDEX "IDX_SALES_ORDER_DELETED" ON "BI_NEGT_KSA"."DMS_SALES_ORDER"("IS_DELETED");
