-- =====================================================
-- Quotation System Database Migration
-- =====================================================
-- Description: Creates all tables required for the quotation system
-- Tables: DMS_QUOTATION, DMS_QUOTATION_LINE_ITEMS, DMS_DISCOUNT_APPROVAL,
--         DMS_QUOTATION_ACTIVITY, and extends DMS_USER_SETTINGS
-- Author: Claude Code
-- Date: 2025-12-26
-- =====================================================

-- =====================================================
-- 1. DMS_QUOTATION - Main Quotation Table
-- =====================================================
CREATE TABLE "BI_NEGT_KSA"."DMS_QUOTATION" (
  -- Primary Key
  "SLNO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

  -- Foreign Keys & References
  "ENQUIRY_SLNO" INTEGER NOT NULL,
  "QUOTATION_NUMBER" NVARCHAR(50) UNIQUE NOT NULL,

  -- Versioning
  "VERSION" INTEGER DEFAULT 1 NOT NULL,
  "PARENT_QUOTATION_SLNO" INTEGER,
  "IS_LATEST_VERSION" NVARCHAR(1) DEFAULT 'Y' NOT NULL,

  -- Customer Information (denormalized for historical record)
  "CUSTOMER_NAME" NVARCHAR(200),
  "CUSTOMER_MOBILE" NVARCHAR(50),
  "CUSTOMER_EMAIL" NVARCHAR(200),
  "CUSTOMER_ADDRESS" NVARCHAR(500),

  -- Vehicle Information (denormalized)
  "VEHICLE_MAKE" NVARCHAR(100),
  "VEHICLE_MODEL" NVARCHAR(100),
  "VEHICLE_VARIANT" NVARCHAR(100),
  "VEHICLE_YEAR" NVARCHAR(10),
  "VEHICLE_COLOR" NVARCHAR(100),
  "VIN_NUMBER" NVARCHAR(100),

  -- Vehicle Pricing
  "VEHICLE_BASE_PRICE" DECIMAL(18,2) DEFAULT 0 NOT NULL,
  "VEHICLE_DISCOUNT" DECIMAL(18,2) DEFAULT 0,
  "VEHICLE_NET_PRICE" DECIMAL(18,2) DEFAULT 0 NOT NULL,

  -- Accessories Pricing
  "ACCESSORIES_TOTAL" DECIMAL(18,2) DEFAULT 0,
  "ACCESSORIES_DISCOUNT" DECIMAL(18,2) DEFAULT 0,
  "ACCESSORIES_NET_TOTAL" DECIMAL(18,2) DEFAULT 0,

  -- Other Pricing Components
  "WARRANTY_TOTAL" DECIMAL(18,2) DEFAULT 0,
  "INSURANCE_TOTAL" DECIMAL(18,2) DEFAULT 0,

  -- Total Calculations
  "SUBTOTAL" DECIMAL(18,2) DEFAULT 0 NOT NULL,
  "TAX_RATE" DECIMAL(5,2) DEFAULT 15.00,
  "TAX_AMOUNT" DECIMAL(18,2) DEFAULT 0 NOT NULL,
  "GRAND_TOTAL" DECIMAL(18,2) DEFAULT 0 NOT NULL,

  -- Trade-in & Financing
  "TRADE_IN_VALUE" DECIMAL(18,2) DEFAULT 0,
  "TRADE_IN_APPRAISAL_SLNO" INTEGER,
  "FINANCING_SCHEME_SLNO" INTEGER,
  "DOWNPAYMENT" DECIMAL(18,2) DEFAULT 0,
  "NET_AMOUNT_DUE" DECIMAL(18,2) DEFAULT 0 NOT NULL,

  -- Discount Summary
  "TOTAL_DISCOUNT_AMOUNT" DECIMAL(18,2) DEFAULT 0,
  "DISCOUNT_PERCENTAGE" DECIMAL(5,2) DEFAULT 0,
  "REQUIRES_APPROVAL" NVARCHAR(1) DEFAULT 'N',
  "DISCOUNT_APPROVAL_STATUS" NVARCHAR(20),
  "DISCOUNT_APPROVED_BY" NVARCHAR(100),
  "DISCOUNT_APPROVED_DATE" NVARCHAR(30),
  "DISCOUNT_APPROVAL_NOTES" NCLOB,

  -- Status & Workflow
  "STATUS" NVARCHAR(20) DEFAULT 'Draft',
  "VALID_UNTIL" NVARCHAR(30),
  "SENT_DATE" NVARCHAR(30),
  "SENT_TO_EMAIL" NVARCHAR(200),

  -- Cashier Handoff
  "PASSED_TO_CASHIER" NVARCHAR(1) DEFAULT 'N',
  "PASSED_TO_CASHIER_DATE" NVARCHAR(30),
  "PASSED_TO_CASHIER_BY" NVARCHAR(100),
  "DEPOSIT_AMOUNT" DECIMAL(18,2) DEFAULT 0,
  "DEPOSIT_COLLECTED" NVARCHAR(1) DEFAULT 'N',

  -- Notes & Terms
  "NOTES" NCLOB,
  "TERMS_AND_CONDITIONS" NCLOB,
  "INTERNAL_NOTES" NCLOB,

  -- Salesperson & Branch
  "SALESPERSON" NVARCHAR(200),
  "SLPCODE" NVARCHAR(50) NOT NULL,
  "BRANCH" NVARCHAR(100),

  -- Audit Fields
  "CREATED_BY" NVARCHAR(100) NOT NULL,
  "CREATED_DATE" NVARCHAR(30) NOT NULL,
  "UPDATED_BY" NVARCHAR(100),
  "UPDATED_DATE" NVARCHAR(30),
  "IS_DELETED" NVARCHAR(1) DEFAULT 'N'
);

-- Indexes for DMS_QUOTATION
CREATE INDEX "IDX_QUOTATION_ENQUIRY" ON "BI_NEGT_KSA"."DMS_QUOTATION"("ENQUIRY_SLNO");
CREATE INDEX "IDX_QUOTATION_NUMBER" ON "BI_NEGT_KSA"."DMS_QUOTATION"("QUOTATION_NUMBER");
CREATE INDEX "IDX_QUOTATION_STATUS" ON "BI_NEGT_KSA"."DMS_QUOTATION"("STATUS");
CREATE INDEX "IDX_QUOTATION_SLPCODE" ON "BI_NEGT_KSA"."DMS_QUOTATION"("SLPCODE");
CREATE INDEX "IDX_QUOTATION_VERSION" ON "BI_NEGT_KSA"."DMS_QUOTATION"("PARENT_QUOTATION_SLNO", "IS_LATEST_VERSION");
CREATE INDEX "IDX_QUOTATION_DELETED" ON "BI_NEGT_KSA"."DMS_QUOTATION"("IS_DELETED");
CREATE INDEX "IDX_QUOTATION_APPROVAL" ON "BI_NEGT_KSA"."DMS_QUOTATION"("DISCOUNT_APPROVAL_STATUS");
CREATE INDEX "IDX_QUOTATION_CREATED_DATE" ON "BI_NEGT_KSA"."DMS_QUOTATION"("CREATED_DATE");

-- =====================================================
-- 2. DMS_QUOTATION_LINE_ITEMS - Quotation Line Items
-- =====================================================
CREATE TABLE "BI_NEGT_KSA"."DMS_QUOTATION_LINE_ITEMS" (
  -- Primary Key
  "SLNO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

  -- Foreign Key
  "QUOTATION_SLNO" INTEGER NOT NULL,

  -- Line Item Details
  "LINE_NUMBER" INTEGER NOT NULL,
  "ITEM_TYPE" NVARCHAR(20) NOT NULL,
  "ITEM_CODE" NVARCHAR(100),
  "ITEM_DESCRIPTION" NVARCHAR(500) NOT NULL,
  "ITEM_CATEGORY" NVARCHAR(100),

  -- Pricing
  "QUANTITY" INTEGER DEFAULT 1 NOT NULL,
  "UNIT_PRICE" DECIMAL(18,2) DEFAULT 0 NOT NULL,
  "DISCOUNT_AMOUNT" DECIMAL(18,2) DEFAULT 0,
  "DISCOUNT_PERCENTAGE" DECIMAL(5,2) DEFAULT 0,
  "NET_PRICE" DECIMAL(18,2) DEFAULT 0 NOT NULL,
  "TAX_INCLUDED" NVARCHAR(1) DEFAULT 'N',

  -- Optional Accessory Details
  "MANUFACTURER" NVARCHAR(100),
  "PART_NUMBER" NVARCHAR(100),
  "WARRANTY_PERIOD" NVARCHAR(50),

  -- Notes
  "NOTES" NCLOB,

  -- Audit Fields
  "CREATED_BY" NVARCHAR(100) NOT NULL,
  "CREATED_DATE" NVARCHAR(30) NOT NULL,
  "UPDATED_BY" NVARCHAR(100),
  "UPDATED_DATE" NVARCHAR(30),
  "IS_DELETED" NVARCHAR(1) DEFAULT 'N'
);

-- Indexes for DMS_QUOTATION_LINE_ITEMS
CREATE INDEX "IDX_LINE_ITEMS_QUOTATION" ON "BI_NEGT_KSA"."DMS_QUOTATION_LINE_ITEMS"("QUOTATION_SLNO");
CREATE INDEX "IDX_LINE_ITEMS_TYPE" ON "BI_NEGT_KSA"."DMS_QUOTATION_LINE_ITEMS"("ITEM_TYPE");
CREATE INDEX "IDX_LINE_ITEMS_DELETED" ON "BI_NEGT_KSA"."DMS_QUOTATION_LINE_ITEMS"("IS_DELETED");
CREATE INDEX "IDX_LINE_ITEMS_LINE_NUMBER" ON "BI_NEGT_KSA"."DMS_QUOTATION_LINE_ITEMS"("QUOTATION_SLNO", "LINE_NUMBER");

-- =====================================================
-- 3. DMS_DISCOUNT_APPROVAL - Discount Approval Workflow
-- =====================================================
CREATE TABLE "BI_NEGT_KSA"."DMS_DISCOUNT_APPROVAL" (
  -- Primary Key
  "SLNO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

  -- Foreign Key
  "QUOTATION_SLNO" INTEGER NOT NULL,

  -- Request Details
  "REQUEST_TYPE" NVARCHAR(20) DEFAULT 'Discount',
  "DISCOUNT_AMOUNT" DECIMAL(18,2) NOT NULL,
  "DISCOUNT_PERCENTAGE" DECIMAL(5,2) NOT NULL,
  "JUSTIFICATION" NCLOB NOT NULL,

  -- User Limits
  "REQUESTED_BY" NVARCHAR(100) NOT NULL,
  "REQUESTED_BY_SLPCODE" NVARCHAR(50) NOT NULL,
  "USER_DISCOUNT_LIMIT" DECIMAL(18,2),
  "AMOUNT_OVER_LIMIT" DECIMAL(18,2),

  -- Approval Workflow
  "STATUS" NVARCHAR(20) DEFAULT 'Pending',
  "ASSIGNED_TO" NVARCHAR(100),
  "ASSIGNED_TO_ROLE" NVARCHAR(50),
  "APPROVED_BY" NVARCHAR(100),
  "APPROVED_BY_SLPCODE" NVARCHAR(50),
  "APPROVED_DATE" NVARCHAR(30),
  "REJECTION_REASON" NCLOB,
  "APPROVAL_NOTES" NCLOB,

  -- Request Timestamp
  "REQUESTED_DATE" NVARCHAR(30) NOT NULL,

  -- Audit Fields
  "CREATED_BY" NVARCHAR(100) NOT NULL,
  "CREATED_DATE" NVARCHAR(30) NOT NULL,
  "UPDATED_BY" NVARCHAR(100),
  "UPDATED_DATE" NVARCHAR(30),
  "IS_DELETED" NVARCHAR(1) DEFAULT 'N'
);

-- Indexes for DMS_DISCOUNT_APPROVAL
CREATE INDEX "IDX_DISCOUNT_APPROVAL_QUOTATION" ON "BI_NEGT_KSA"."DMS_DISCOUNT_APPROVAL"("QUOTATION_SLNO");
CREATE INDEX "IDX_DISCOUNT_APPROVAL_STATUS" ON "BI_NEGT_KSA"."DMS_DISCOUNT_APPROVAL"("STATUS");
CREATE INDEX "IDX_DISCOUNT_APPROVAL_ASSIGNED" ON "BI_NEGT_KSA"."DMS_DISCOUNT_APPROVAL"("ASSIGNED_TO");
CREATE INDEX "IDX_DISCOUNT_APPROVAL_REQUESTED" ON "BI_NEGT_KSA"."DMS_DISCOUNT_APPROVAL"("REQUESTED_BY_SLPCODE");
CREATE INDEX "IDX_DISCOUNT_APPROVAL_DELETED" ON "BI_NEGT_KSA"."DMS_DISCOUNT_APPROVAL"("IS_DELETED");
CREATE INDEX "IDX_DISCOUNT_APPROVAL_REQUESTED_DATE" ON "BI_NEGT_KSA"."DMS_DISCOUNT_APPROVAL"("REQUESTED_DATE");

-- =====================================================
-- 4. DMS_QUOTATION_ACTIVITY - Activity Log
-- =====================================================
CREATE TABLE "BI_NEGT_KSA"."DMS_QUOTATION_ACTIVITY" (
  -- Primary Key
  "SLNO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

  -- Foreign Key
  "QUOTATION_SLNO" INTEGER NOT NULL,

  -- Activity Details
  "ACTIVITY_TYPE" NVARCHAR(50) NOT NULL,
  "ACTIVITY_DESCRIPTION" NVARCHAR(500),
  "ACTIVITY_NOTES" NCLOB,

  -- Follow-up Task
  "IS_FOLLOW_UP" NVARCHAR(1) DEFAULT 'N',
  "FOLLOW_UP_DATE" NVARCHAR(30),
  "FOLLOW_UP_ASSIGNED_TO" NVARCHAR(100),
  "FOLLOW_UP_STATUS" NVARCHAR(20) DEFAULT 'Pending',
  "FOLLOW_UP_COMPLETED_DATE" NVARCHAR(30),

  -- Audit
  "CREATED_BY" NVARCHAR(100) NOT NULL,
  "CREATED_DATE" NVARCHAR(30) NOT NULL,
  "IS_DELETED" NVARCHAR(1) DEFAULT 'N'
);

-- Indexes for DMS_QUOTATION_ACTIVITY
CREATE INDEX "IDX_ACTIVITY_QUOTATION" ON "BI_NEGT_KSA"."DMS_QUOTATION_ACTIVITY"("QUOTATION_SLNO");
CREATE INDEX "IDX_ACTIVITY_TYPE" ON "BI_NEGT_KSA"."DMS_QUOTATION_ACTIVITY"("ACTIVITY_TYPE");
CREATE INDEX "IDX_ACTIVITY_FOLLOW_UP" ON "BI_NEGT_KSA"."DMS_QUOTATION_ACTIVITY"("IS_FOLLOW_UP", "FOLLOW_UP_STATUS");
CREATE INDEX "IDX_ACTIVITY_DELETED" ON "BI_NEGT_KSA"."DMS_QUOTATION_ACTIVITY"("IS_DELETED");
CREATE INDEX "IDX_ACTIVITY_CREATED_DATE" ON "BI_NEGT_KSA"."DMS_QUOTATION_ACTIVITY"("CREATED_DATE");







  -- Update Soumya's discount limit to 10,000 SAR


--  UPDATE "BI_NEGT_KSA"."DMS_USER_SETTINGS"
--   SET "DISCOUNT_LIMIT_AMOUNT" = 10000,
--       "DISCOUNT_LIMIT_PERCENTAGE" = 10,
--       "USER_ROLE" = 'Salesperson',
--       "UPDATED_BY" = 'SYSTEM',
--       "UPDATED_DATE" = CURRENT_TIMESTAMP
--   WHERE "USER_ID" = 'Soumya';




-- =====================================================
-- 5. Extend DMS_USER_SETTINGS for Discount Limits
-- =====================================================
-- Note: If DMS_USER_SETTINGS table doesn't exist yet,
-- you'll need to create it first or store discount limits
-- in the JWT token payload or a separate config table

-- Check if the table exists before altering
-- DO $$
-- BEGIN
--   IF EXISTS (SELECT 1 FROM TABLES WHERE SCHEMA_NAME = 'BI_NEGT_KSA' AND TABLE_NAME = 'DMS_USER_SETTINGS') THEN
--     EXECUTE 'ALTER TABLE "BI_NEGT_KSA"."DMS_USER_SETTINGS" ADD ("DISCOUNT_LIMIT_AMOUNT" DECIMAL(18,2) DEFAULT 0)';
--     EXECUTE 'ALTER TABLE "BI_NEGT_KSA"."DMS_USER_SETTINGS" ADD ("DISCOUNT_LIMIT_PERCENTAGE" DECIMAL(5,2) DEFAULT 0)';
--   END IF;
-- END $$;

-- For SAP HANA, use this approach instead:
-- ALTER TABLE "BI_NEGT_KSA"."DMS_USER_SETTINGS"
-- ADD ("DISCOUNT_LIMIT_AMOUNT" DECIMAL(18,2) DEFAULT 0);

-- ALTER TABLE "BI_NEGT_KSA"."DMS_USER_SETTINGS"
-- ADD ("DISCOUNT_LIMIT_PERCENTAGE" DECIMAL(5,2) DEFAULT 0);

-- =====================================================
-- Comments on Tables
-- =====================================================
COMMENT ON TABLE "BI_NEGT_KSA"."DMS_QUOTATION" IS 'Main quotation table storing vehicle sales quotations with pricing, discounts, and approval workflow';
COMMENT ON TABLE "BI_NEGT_KSA"."DMS_QUOTATION_LINE_ITEMS" IS 'Line items for quotations including vehicle, accessories, warranties, and services';
COMMENT ON TABLE "BI_NEGT_KSA"."DMS_DISCOUNT_APPROVAL" IS 'Discount approval workflow tracking for quotations exceeding user limits';
COMMENT ON TABLE "BI_NEGT_KSA"."DMS_QUOTATION_ACTIVITY" IS 'Activity log and follow-up tasks for quotations';

-- =====================================================
-- Sample Discount Limits (Optional)
-- =====================================================
-- These can be inserted into DMS_USER_SETTINGS or managed via application config

-- Example role-based limits:
-- Salesperson: 5,000 SAR
-- Senior Salesperson: 10,000 SAR
-- Sales Manager: 25,000 SAR
-- Sales Director: 50,000 SAR
-- General Manager: Unlimited (999,999,999 SAR)

-- =====================================================
-- Foreign Key Constraints (Optional - depends on your DB setup)
-- =====================================================
-- Note: SAP HANA supports foreign keys but they are optional
-- Uncomment if you want to enforce referential integrity

-- ALTER TABLE "BI_NEGT_KSA"."DMS_QUOTATION"
-- ADD CONSTRAINT "FK_QUOTATION_ENQUIRY"
-- FOREIGN KEY ("ENQUIRY_SLNO")
-- REFERENCES "BI_NEGT_KSA"."DMS_SALESENQUIRY"("SLNO");

-- ALTER TABLE "BI_NEGT_KSA"."DMS_QUOTATION"
-- ADD CONSTRAINT "FK_QUOTATION_PARENT"
-- FOREIGN KEY ("PARENT_QUOTATION_SLNO")
-- REFERENCES "BI_NEGT_KSA"."DMS_QUOTATION"("SLNO");

-- ALTER TABLE "BI_NEGT_KSA"."DMS_QUOTATION_LINE_ITEMS"
-- ADD CONSTRAINT "FK_LINE_ITEMS_QUOTATION"
-- FOREIGN KEY ("QUOTATION_SLNO")
-- REFERENCES "BI_NEGT_KSA"."DMS_QUOTATION"("SLNO");

-- ALTER TABLE "BI_NEGT_KSA"."DMS_DISCOUNT_APPROVAL"
-- ADD CONSTRAINT "FK_DISCOUNT_QUOTATION"
-- FOREIGN KEY ("QUOTATION_SLNO")
-- REFERENCES "BI_NEGT_KSA"."DMS_QUOTATION"("SLNO");

-- ALTER TABLE "BI_NEGT_KSA"."DMS_QUOTATION_ACTIVITY"
-- ADD CONSTRAINT "FK_ACTIVITY_QUOTATION"
-- FOREIGN KEY ("QUOTATION_SLNO")
-- REFERENCES "BI_NEGT_KSA"."DMS_QUOTATION"("SLNO");

-- =====================================================
-- Migration Complete
-- =====================================================
-- Execute this script in SAP HANA Studio or via SQL Console
-- Verify all tables created successfully:
-- SELECT TABLE_NAME FROM TABLES WHERE SCHEMA_NAME = 'BI_NEGT_KSA' AND TABLE_NAME LIKE 'DMS_%QUOTATION%';
